<?php
$active = (null === $this->active) ? 1 : $this->active;
?>
<div class="title">
    <h3 style="cursor: s-resize;">Articles</h3>
    <div title="content_box" class="selector hide_div">
        <a href="add" class="tab <?=($active == 1) ? 'active' : '' ?>">Add a article</a>
        <a href="/index/index" class="tab">List Articles</a>
    </div>
</div>

<div class="box">
    <div class="txt">
        <div id="content_box">
            <div class="add hide_div">
                <?php echo $this->form;?>

            </div>
        </div>
    </div>
</div>
