<?php
$active = (null === $this->active) ? 1 : $this->active;
?>
<div class="title">
    <h3 style="cursor: s-resize;">Articles</h3>
    <div title="content_box" class="selector hide_div">
        <a href="tab-upload" class="tab <?=($active == 1) ? 'active' : '' ?>">Edit article</a>
    </div>
</div>

<div class="box">
    <div class="txt">
        <div id="content_box">
            <div class="tab-upload hide_div">
                <?php echo $this->form;?>

            </div>
        </div>
    </div>
</div>
