<?php
$active = (null === $this->active) ? 1 : $this->active;
?>
<div class="title">
    <h3 style="cursor: s-resize;">Article List</h3>
    <div title="content_box" class="selector hide_div">
        <a href="index" class="tab <?=($active == 1) ? 'active' : '' ?>">Article List</a>
        <a href="/index/add" class="tab">Add a Article</a>
    </div>
</div>

<div class="box">
    <div class="txt">
        <div id="content_box">
                                <div class="index hide_div" style="display: block;">
                                   
           
                                                  <?php 
                                                  $flashMessenger = $this->flashMessenger;
                                                  if($flashMessenger->hasMessages('success')): ?>
                                                      <div class="message success">
                                                      <?php foreach($flashMessenger->getMessages('success') as $msg): ?>
                                                          <?php echo '<p>'.$msg.'</p>' ?>
                                                      <?php endforeach; ?>
                                                      </div>
                                                      <?php endif; ?>
                                       

                                                      <?php if($this->is_article_empty)  { ?>

                                                     <div class="message error">
                                                     <p>No Articles has been added yet.!</p>
                                                      </div>
                                                      
                                                      
                                                      <?php } else { ?>
                                                      
                                                     

                                                      
                                    <!-- Start Table -->
                                    <table cellspacing="0" cellpadding="0">
                                        <thead>
                                            <tr>
                                                <th><input type="checkbox" name="check"></th>
                                                <th>Name</th>
                                                <th>Text</th>
                                                <th>Email</th>
                                                <th>Added Date</th>
                                                <th>Operations</th>
                                            </tr>
                                            
                                            
                                        </thead>
                                        <tbody>
                                        
                                         <?foreach($this->articles as $article): ?>

                                         <?=$this->partial('partials/article.phtml',array("article" => $article )); ?>
                        
                                         <?endforeach; ?>
                                         
                                       
                                                
                                           
                                        </tbody>
                                    </table>
                                    <!-- End Table -->
                                    
                                      <?=$this->paginationControl($this->articles, 'Sliding', 'partials/paginator.phtml',array()); ?> 
                                      
                                       <?php }?>

                                </div>
                              
                            </div>
    </div>
</div>
